version: '3.9'

services:
  backend:
    build:
        context: ../.
        dockerfile: docker/Dockerfile
    restart: always
    env_file:
        - ../.env
    depends_on:
        - db
    ports:
        - "9999:9999"
    volumes:
        - ../src/static:/code/static
  db:
    image: postgres:15
    env_file:
        - ../.env
    restart: always
    # command: -p 5433
    volumes:
        - ./data:/var/lib/postgresql/data
    ports:
        - "5432:5432"